// Genera los iconos PNG de la PWA sin dependencias externas (solo node:zlib).
// Se ejecuta como paso "prebuild" en CI/Docker; no requiere herramientas gráficas.
import { deflateSync } from 'node:zlib';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import designTokens from '../src/styles/designTokens.json' with { type: 'json' };

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'public');
mkdirSync(outDir, { recursive: true });

const generatedTokenCss = `/* Generated by scripts/generate-icons.mjs from designTokens.json.
 * Hallmark · theme: custom Telón · pre-emit critique: P5 H4 E4 S5 R5 V5
 */
:root {
${Object.entries(designTokens).map(([name, value]) => `  --${name}: ${value};`).join('\n')}
}
`;
writeFileSync(join(root, 'src/styles/designTokens.css'), generatedTokenCss);

const CRC_TABLE = new Int32Array(256).map((_, n) => {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c;
});

function crc32(buf) {
  let c = 0xffffffff;
  for (const b of buf) c = CRC_TABLE[(c ^ b) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function chunk(type, data) {
  const t = Buffer.from(type, 'ascii');
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(Buffer.concat([t, data])));
  return Buffer.concat([len, t, data, crc]);
}

function writePng(path, size, pixelAt) {
  const raw = Buffer.alloc(size * (size * 4 + 1));
  let off = 0;
  for (let y = 0; y < size; y++) {
    raw[off++] = 0;
    for (let x = 0; x < size; x++) {
      const [r, g, b, a] = pixelAt(x, y);
      raw[off++] = r;
      raw[off++] = g;
      raw[off++] = b;
      raw[off++] = a;
    }
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0);
  ihdr.writeUInt32BE(size, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // RGBA
  const png = Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0))
  ]);
  writeFileSync(path, png);
  console.log(`wrote ${path} (${size}x${size})`);
}

function hexColor(value) {
  const hex = value.replace(/^#/, '');
  if (hex.length !== 6) throw new Error(`Expected a six-digit color, received ${value}`);
  return [
    Number.parseInt(hex.slice(0, 2), 16),
    Number.parseInt(hex.slice(2, 4), 16),
    Number.parseInt(hex.slice(4, 6), 16),
    255
  ];
}

const BG = hexColor(designTokens.bg);
const MARK_COLORS = {
  G: hexColor(designTokens.accent),
  D: hexColor(designTokens['gold-shade']),
  B: hexColor(designTokens.text)
};

// Telón en pixel art (manual de identidad, "Tamaños ópticos"). Son dos dibujos
// hechos para su tamaño, no una reducción: 32 módulos para los íconos de inicio
// y 16 para el favicon. Leyenda: G dorado, D oro sombra, B hueso, . fondo.
const MARK_32 = [
  '................................',
  '................................',
  '.GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.',
  '.GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.',
  '.GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.',
  '.GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.',
  '.GGDDGGDDGGDDGGDDGGDDGGDDGGDDGG.',
  '.GDGDGDGDGD..........DGDGDGDGDG.',
  '.GDGDGDGDGD..........DGDGDGDGDG.',
  '.GDGDGDGDG............GDGDGDGDG.',
  '.GDGDGDGDG............GDGDGDGDG.',
  '.GDGDGDGDG............GDGDGDGDG.',
  '.GDGDGDGD..............DGDGDGDG.',
  '.GDGDGDGD..............DGDGDGDG.',
  '.GDGDGDGD..............DGDGDGDG.',
  '.GDGDGDG................GDGDGDG.',
  '.GDGDGDG................GDGDGDG.',
  '.GDGDGD..................DGDGDG.',
  '.GDGDGD..................DGDGDG.',
  '.GDGDGD..................DGDGDG.',
  '.GDGDG....................GDGDG.',
  '.BBBBBB..................BBBBBB.',
  '.BBBBBB..................BBBBBB.',
  '.GDGDGD..................DGDGDG.',
  '.GDGDGD..................DGDGDG.',
  '.GDGDGD..................DGDGDG.',
  '.GDGDGD..................DGDGDG.',
  '.GDGDGD..................DGDGDG.',
  '.GDGDGDG................GDGDGDG.',
  '.GDGDGDG................GDGDGDG.',
  '................................',
  '................................'
];

const MARK_16 = [
  '................',
  'GGGGGGGGGGGGGGGG',
  'GGGGGGGGGGGGGGGG',
  'GDGDGDGDGDGDGDGD',
  'GDGDG......GDGDG',
  'GDGDG......GDGDG',
  'GDGD........DGDG',
  'GDGD........DGDG',
  'GDG..........GDG',
  'GBB..........BBG',
  'GDG..........GDG',
  'GDGD........DGDG',
  'GDGD........DGDG',
  'GDGDG......GDGDG',
  'GDGDG......GDGDG',
  '................'
];

// Escala la marca por un entero y la centra con un margen de fondo, para que
// cada módulo caiga en píxeles exactos. El fondo siempre llega al borde.
function pixelMark(rows, scale, margin) {
  return (x, y) => {
    const cell = rows[Math.floor((y - margin) / scale)]?.[Math.floor((x - margin) / scale)];
    return MARK_COLORS[cell] ?? BG;
  };
}

writePng(join(outDir, 'icon-192.png'), 192, pixelMark(MARK_32, 5, 16));
writePng(join(outDir, 'icon-512.png'), 512, pixelMark(MARK_32, 14, 32));
// Maskable: ×9 deja la marca dentro del círculo seguro del 80 %.
writePng(join(outDir, 'icon-512-maskable.png'), 512, pixelMark(MARK_32, 9, 112));
writePng(join(outDir, 'apple-touch-icon.png'), 180, pixelMark(MARK_32, 5, 10));

function svgRects(rows) {
  const rects = [];
  rows.forEach((row, y) => {
    for (let x = 0; x < row.length; ) {
      const color = MARK_COLORS[row[x]];
      if (!color) {
        x += 1;
        continue;
      }
      let end = x;
      while (end < row.length && MARK_COLORS[row[end]] === color) end += 1;
      rects.push(`  <rect x="${x}" y="${y}" width="${end - x}" height="1" fill="#${color.slice(0, 3).map((c) => c.toString(16).padStart(2, '0')).join('')}"/>`);
      x = end;
    }
  });
  return rects.join('\n');
}

writeFileSync(
  join(outDir, 'favicon.svg'),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" shape-rendering="crispEdges">
  <rect width="16" height="16" fill="${designTokens.bg}"/>
${svgRects(MARK_16)}
</svg>
`
);
