// Genera los iconos PNG de la PWA sin dependencias externas (solo node:zlib).
// Se ejecuta como paso "prebuild" en CI/Docker; no requiere herramientas gráficas.
import { deflateSync } from 'node:zlib';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import designTokens from '../src/styles/designTokens.json' with { type: 'json' };

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'public');
mkdirSync(outDir, { recursive: true });

const generatedTokenCss = `/* Generated by scripts/generate-icons.mjs from designTokens.json.
 * Hallmark · theme: custom Telón · pre-emit critique: P5 H4 E4 S5 R5 V5
 */
:root {
${Object.entries(designTokens).map(([name, value]) => `  --${name}: ${value};`).join('\n')}
}
`;
writeFileSync(join(root, 'src/styles/designTokens.css'), generatedTokenCss);

const CRC_TABLE = new Int32Array(256).map((_, n) => {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c;
});

function crc32(buf) {
  let c = 0xffffffff;
  for (const b of buf) c = CRC_TABLE[(c ^ b) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function chunk(type, data) {
  const t = Buffer.from(type, 'ascii');
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(Buffer.concat([t, data])));
  return Buffer.concat([len, t, data, crc]);
}

function writePng(path, size, pixelAt) {
  const raw = Buffer.alloc(size * (size * 4 + 1));
  let off = 0;
  for (let y = 0; y < size; y++) {
    raw[off++] = 0;
    for (let x = 0; x < size; x++) {
      const [r, g, b, a] = pixelAt(x, y);
      raw[off++] = r;
      raw[off++] = g;
      raw[off++] = b;
      raw[off++] = a;
    }
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0);
  ihdr.writeUInt32BE(size, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // RGBA
  const png = Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0))
  ]);
  writeFileSync(path, png);
  console.log(`wrote ${path} (${size}x${size})`);
}

function hexColor(value) {
  const hex = value.replace(/^#/, '');
  if (hex.length !== 6) throw new Error(`Expected a six-digit color, received ${value}`);
  return [
    Number.parseInt(hex.slice(0, 2), 16),
    Number.parseInt(hex.slice(2, 4), 16),
    Number.parseInt(hex.slice(4, 6), 16),
    255
  ];
}

const BG = hexColor(designTokens.bg);
const STAGE = hexColor(designTokens['reading-bg']);
const ACCENT = hexColor(designTokens.accent);
const SAMPLES = 4;

// Arco de proscenio: rectángulo con remate semicircular, centrado en x=32 y con
// arranque en y=28, medido en el lienzo de 64 unidades del favicon.
function inArch(u, v, halfWidth, bottom) {
  if (v > bottom || Math.abs(u - 32) > halfWidth) return false;
  return v >= 28 || (u - 32) ** 2 + (v - 28) ** 2 <= halfWidth ** 2;
}

function markColor(u, v) {
  if (u >= 10 && u <= 54 && v >= 46 && v <= 50) return ACCENT;
  if (inArch(u, v, 15, 48)) return inArch(u, v, 11, 44) ? STAGE : ACCENT;
  return BG;
}

// El escenario abierto sobre el telón, con esquinas rectas. `pad` encoge la marca
// hacia la zona segura de los iconos maskable; el fondo siempre llega al borde.
function icon(size, { pad }) {
  const scale = 64 / (1 - 2 * pad);
  return (x, y) => {
    const sum = [0, 0, 0];
    for (let sy = 0; sy < SAMPLES; sy++) {
      for (let sx = 0; sx < SAMPLES; sx++) {
        const u = ((x + (sx + 0.5) / SAMPLES) / size - pad) * scale;
        const v = ((y + (sy + 0.5) / SAMPLES) / size - pad) * scale;
        const color = markColor(u, v);
        for (let channel = 0; channel < 3; channel++) sum[channel] += color[channel];
      }
    }
    return [...sum.map((value) => Math.round(value / SAMPLES ** 2)), 255];
  };
}

writePng(join(outDir, 'icon-192.png'), 192, icon(192, { pad: 0 }));
writePng(join(outDir, 'icon-512.png'), 512, icon(512, { pad: 0 }));
writePng(join(outDir, 'icon-512-maskable.png'), 512, icon(512, { pad: 0.12 }));
writePng(join(outDir, 'apple-touch-icon.png'), 180, icon(180, { pad: 0 }));

writeFileSync(
  join(outDir, 'favicon.svg'),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <rect width="64" height="64" fill="${designTokens.bg}"/>
  <path d="M19 46V28A13 13 0 0 1 45 28V46Z" fill="${designTokens['reading-bg']}" stroke="${designTokens.accent}" stroke-width="4"/>
  <path d="M10 48H54" stroke="${designTokens.accent}" stroke-width="4"/>
</svg>
`
);
